# Bu iş akışı, bir Golang projesini derleyecektir.
# Daha fazla bilgi için: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
    - name: Kodları kontrol et
      uses: actions/setup-go@v4

    - name: Go'yu kur
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.1'

    - name: Bağımlılıkları yükle
      run: go mod tidy

    - name: Derle
      run: go build -v ./...

    - name: Test et
      run: go test -v ./...
      env:
        MONGODB_URI: mongodb://localhost:27017