name: Go CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password123

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Create config file
      run: |
        mkdir -p config
        echo "mongoDbConnect: \"mongodb://admin:password123@localhost:27017\"" > config/config.yaml
        echo "bootIdTelegram: \"${{ secrets.TELEGRAM_BOT_TOKEN }}\"" >> config/config.yaml
        echo "dbName: \"telegram\"" >> config/config.yaml
        echo "apiDomain: \"sadiksunbul.com/\"" >> config/config.yaml

    - name: Install dependencies
      run: go mod download

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./... 